apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-pvc
  namespace: plex
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Ti
  volumeName: plex-media-pv
